import React, { useState, useEffect } from 'react';
import { useParams, useLocation, useNavigate } from 'react-router-dom';
import { Card, Typography, Tag, Alert, Button, Space, Row, Col, Divider, Timeline, Avatar, Tooltip, Badge } from 'antd';
import { 
  WarningOutlined, 
  CheckCircleOutlined, 
  ExclamationCircleOutlined, 
  CrownOutlined,
  ArrowLeftOutlined,
  FilePdfOutlined,
  BulbOutlined,
  FireOutlined,
  InfoCircleOutlined,
  CheckOutlined
} from '@ant-design/icons';
import HealthScoreGauge from '../components/HealthScoreGauge';
import { LoadingSpinner } from '../components/Loading';
import { ErrorPage } from '../components/Error';

const { Title, Text, Paragraph } = Typography;

interface Issue {
  type: 'critical' | 'high' | 'medium' | 'low';
  title: string;
  description: string;
  fix: string;
}

const Analysis: React.FC = () => {
  const { id } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [analysisNotFound, setAnalysisNotFound] = useState(false);
  
  // Get analysis from location state or localStorage
  const getAnalysisData = () => {
    // First try location state
    if (location.state?.analysis) {
      return location.state.analysis;
    }
    
    // Then try localStorage
    const historyStr = localStorage.getItem('analysis_history');
    if (historyStr && id) {
      const history = JSON.parse(historyStr);
      const found = history.find((item: any) => item.id === id);
      if (found) {
        return found;
      }
    }
    
    // Not found
    return null;
  };

  const rawAnalysis = getAnalysisData();
  
  useEffect(() => {
    // Simulate loading delay
    const timer = setTimeout(() => {
      setLoading(false);
      if (!rawAnalysis) {
        setAnalysisNotFound(true);
      }
    }, 500);
    
    return () => clearTimeout(timer);
  }, [rawAnalysis]);

  // Download report as text file
  const handleDownloadReport = () => {
    if (!analysis) return;
    
    const reportDate = new Date().toLocaleString();
    const issues = analysis.issues || [];
    
    let report = `
═══════════════════════════════════════════════════════════════
                 GHL WORKFLOW ANALYSIS REPORT
═══════════════════════════════════════════════════════════════

Workflow: ${analysis.workflow_name || analysis.workflowName || 'Unknown'}
Generated: ${reportDate}
Analysis ID: ${analysis.id || id}

───────────────────────────────────────────────────────────────
                        HEALTH SCORE
───────────────────────────────────────────────────────────────

Score: ${analysis.healthScore}/100
Grade: ${analysis.grade}
Issues Found: ${analysis.issuesFound}

───────────────────────────────────────────────────────────────
                      ISSUES DETECTED
───────────────────────────────────────────────────────────────

`;

    issues.forEach((issue: Issue, index: number) => {
      report += `
${index + 1}. [${issue.type.toUpperCase()}] ${issue.title}
   Description: ${issue.description}
   Recommended Fix: ${issue.fix}
`;
    });

    report += `
───────────────────────────────────────────────────────────────
                        SUMMARY
───────────────────────────────────────────────────────────────

Critical Issues: ${issues.filter((i: Issue) => i.type === 'critical').length}
High Priority: ${issues.filter((i: Issue) => i.type === 'high').length}
Medium Priority: ${issues.filter((i: Issue) => i.type === 'medium').length}
Low Priority: ${issues.filter((i: Issue) => i.type === 'low').length}

═══════════════════════════════════════════════════════════════
        Generated by WorkflowMD
        https://ghlworkflowdebugger.com
═══════════════════════════════════════════════════════════════
`;

    // Create and download file
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `workflow-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  // Helper to calculate grade from score
  const calculateGrade = (score: number) => {
    if (score >= 90) return 'Excellent';
    if (score >= 70) return 'Good';
    if (score >= 50) return 'Needs Attention';
    if (score >= 30) return 'High Risk';
    return 'Critical';
  };

  // Show loading state
  if (loading) {
    return (
      <LoadingSpinner
        message="Loading Analysis Results"
        tip="Fetching your workflow analysis data..."
        size="large"
      />
    );
  }

  // Show error if analysis not found
  if (analysisNotFound || !rawAnalysis) {
    return (
      <ErrorPage
        message="Analysis Not Found"
        error={new Error(`Analysis with ID ${id} could not be found`)}
        onRetry={() => {
          navigate('/dashboard');
        }}
        showHomeButton={true}
        showRetryButton={false}
      />
    );
  }

  // Normalize data - handle both snake_case and camelCase
  const healthScore = rawAnalysis.healthScore ?? rawAnalysis.health_score ?? 50;
  const analysis = {
    ...rawAnalysis,
    healthScore,
    grade: calculateGrade(healthScore), // Always recalculate grade from score
    issuesFound: rawAnalysis.issuesFound ?? rawAnalysis.issues_found ?? rawAnalysis.issues?.length ?? 0
  };

  const getSeverityIcon = (type: string) => {
    const iconStyle = { fontSize: '20px' };
    switch (type) {
      case 'critical':
        return <ExclamationCircleOutlined style={{ ...iconStyle, color: '#ff4d4f' }} />;
      case 'high':
        return <FireOutlined style={{ ...iconStyle, color: '#fa8c16' }} />;
      case 'medium':
        return <WarningOutlined style={{ ...iconStyle, color: '#faad14' }} />;
      default:
        return <CheckCircleOutlined style={{ ...iconStyle, color: '#52c41a' }} />;
    }
  };

  const getSeverityColor = (type: string) => {
    switch (type) {
      case 'critical':
        return '#ff4d4f';
      case 'high':
        return '#fa8c16';
      case 'medium':
        return '#faad14';
      default:
        return '#52c41a';
    }
  };

  const getHealthLevel = (score: number) => {
    // Higher score = better health
    if (score >= 90) return 'Excellent';
    if (score >= 70) return 'Good';
    if (score >= 50) return 'Needs Attention';
    if (score >= 30) return 'High Risk';
    return 'Critical';
  };

  return (
    <div>
      {/* Navigation */}
      <Button 
        icon={<ArrowLeftOutlined />} 
        onClick={() => navigate('/dashboard')}
        style={{ marginBottom: '24px' }}
      >
        Back to Dashboard
      </Button>

      {/* Hero Card with Risk Score */}
      <Card style={{ 
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        border: 'none',
        marginBottom: '24px',
        color: 'white'
      }}>
        <Row gutter={[24, 24]} align="middle">
          <Col xs={24} lg={8}>
            <div style={{ display: 'flex', justifyContent: 'center' }}>
              <HealthScoreGauge 
                score={analysis.healthScore}
                title="Workflow Health"
                size="large"
                animated={true}
              />
            </div>
          </Col>
          
          <Col xs={24} lg={16}>
            <Space direction="vertical" size="large" style={{ width: '100%' }}>
              <div>
                <Title level={2} style={{ color: 'white', margin: 0 }}>
                  Workflow Analysis Complete
                </Title>
                <Paragraph style={{ color: 'rgba(255,255,255,0.9)', fontSize: '16px', marginTop: '8px' }}>
                  We've analyzed your workflow and found {analysis.issuesFound || analysis.issues?.length} issues that need attention.
                </Paragraph>
              </div>
              
              <Row gutter={[24, 0]}>
                <Col xs={12} sm={6}>
                  <Statistic 
                    title="Health Level" 
                    value={getHealthLevel(analysis.healthScore)}
                    valueStyle={{ color: 'white', fontSize: '18px' }}
                    titleStyle={{ color: 'rgba(255,255,255,0.8)' }}
                  />
                </Col>
                <Col xs={12} sm={6}>
                  <Statistic 
                    title="Issues Found" 
                    value={analysis.issuesFound || analysis.issues?.length}
                    valueStyle={{ color: 'white', fontSize: '24px' }}
                    titleStyle={{ color: 'rgba(255,255,255,0.8)' }}
                  />
                </Col>
                <Col xs={12} sm={6}>
                  <Statistic 
                    title="Critical" 
                    value={analysis.issues?.filter((i: Issue) => i.type === 'critical').length || 0}
                    valueStyle={{ color: 'white', fontSize: '24px' }}
                    titleStyle={{ color: 'rgba(255,255,255,0.8)' }}
                  />
                </Col>
                <Col xs={12} sm={6}>
                  <Statistic 
                    title="High Priority" 
                    value={analysis.issues?.filter((i: Issue) => i.type === 'high').length || 0}
                    valueStyle={{ color: 'white', fontSize: '24px' }}
                    titleStyle={{ color: 'rgba(255,255,255,0.8)' }}
                  />
                </Col>
              </Row>
            </Space>
          </Col>
        </Row>
      </Card>

      {/* Upgrade Alert for Free Users */}
      {analysis.upgradePrompt && (
        <Alert
          message={
            <Space>
              <CrownOutlined />
              <Text strong>{analysis.upgradePrompt.hidden} more issues found in your workflow</Text>
            </Space>
          }
          description="Upgrade to Pro to see all issues with detailed fixes and get white-label reports for your clients."
          type="warning"
          action={
            <Space direction="vertical">
              <Button type="primary" icon={<CrownOutlined />} onClick={() => navigate('/pricing')}>
                Upgrade to Pro
              </Button>
              <Button icon={<FilePdfOutlined />} disabled>
                PDF Report (Pro Only)
              </Button>
            </Space>
          }
          showIcon={false}
          style={{ marginBottom: '24px' }}
        />
      )}

      <Row gutter={[24, 24]}>
        <Col xs={24} lg={16}>
          {/* Issues List */}
          <Card 
            title={
              <Space>
                <BulbOutlined style={{ color: '#667eea' }} />
                <span>Issues Detected</span>
                {analysis.upgradePrompt && (
                  <Tag color="orange">Showing 3 of {(analysis.issuesFound || 8)} issues</Tag>
                )}
              </Space>
            }
          >
            {analysis.issues && analysis.issues.length > 0 ? (
              <Timeline>
                {analysis.issues.map((issue: Issue, index: number) => (
                  <Timeline.Item
                    key={index}
                    dot={getSeverityIcon(issue.type)}
                  >
                    <Card 
                      hoverable
                      style={{ 
                        marginBottom: '16px',
                        borderLeft: `4px solid ${getSeverityColor(issue.type)}`,
                        transition: 'all 0.3s ease',
                        animation: `fadeInUp 0.5s ease backwards ${index * 0.1}s`
                      }}
                      bodyStyle={{ padding: '20px' }}
                    >
                      <Space direction="vertical" style={{ width: '100%' }} size="middle">
                        {/* Header */}
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                          <Space align="start" size="middle">
                            <Badge 
                              count={getSeverityIcon(issue.type)} 
                              style={{ 
                                background: getSeverityColor(issue.type),
                                boxShadow: `0 0 0 3px ${getSeverityColor(issue.type)}20`
                              }}
                            />
                            <div>
                              <Text strong style={{ fontSize: '18px', display: 'block', marginBottom: '4px' }}>
                                {issue.title}
                              </Text>
                              <Tag color={
                                issue.type === 'critical' ? 'error' :
                                issue.type === 'high' ? 'orange' :
                                issue.type === 'medium' ? 'warning' : 'success'
                              }>
                                {issue.type.toUpperCase()} PRIORITY
                              </Tag>
                            </div>
                          </Space>
                          <Tooltip title="Issue details">
                            <InfoCircleOutlined style={{ fontSize: '20px', color: '#8c8c8c', cursor: 'pointer' }} />
                          </Tooltip>
                        </div>
                        
                        {/* Description */}
                        <div style={{ 
                          padding: '12px 16px',
                          background: 'rgba(0,0,0,0.02)',
                          borderRadius: '8px',
                          borderLeft: '3px solid rgba(0,0,0,0.1)'
                        }}>
                          <Text style={{ fontSize: '15px', lineHeight: '1.6', color: '#595959' }}>
                            {issue.description}
                          </Text>
                        </div>
                        
                        <Divider style={{ margin: '8px 0' }} />
                        
                        {/* Recommended Fix */}
                        <div style={{ 
                          background: 'linear-gradient(135deg, #f6ffed 0%, #e8f9e8 100%)', 
                          border: '1px solid #b7eb8f',
                          borderRadius: '10px',
                          padding: '16px',
                          boxShadow: '0 2px 8px rgba(82, 196, 26, 0.1)'
                        }}>
                          <Space align="start" size="middle" style={{ width: '100%' }}>
                            <div style={{
                              width: '32px',
                              height: '32px',
                              borderRadius: '50%',
                              background: '#52c41a',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                              flexShrink: 0
                            }}>
                              <CheckOutlined style={{ color: 'white', fontSize: '16px' }} />
                            </div>
                            <div style={{ flex: 1 }}>
                              <Text strong style={{ color: '#52c41a', fontSize: '15px', display: 'block', marginBottom: '8px' }}>
                                💡 Recommended Fix
                              </Text>
                              <Text style={{ fontSize: '14px', lineHeight: '1.6', color: '#389e0d' }}>
                                {issue.fix}
                              </Text>
                            </div>
                          </Space>
                        </div>
                      </Space>
                    </Card>
                  </Timeline.Item>
                ))}
              </Timeline>
            ) : (
              <Alert
                message="No issues found!"
                description="Your workflow is perfectly configured. Great job!"
                type="success"
                showIcon
                icon={<CheckCircleOutlined />}
              />
            )}
          </Card>
        </Col>

        <Col xs={24} lg={8}>
          {/* Summary Card */}
          <Card 
            title="Analysis Summary"
            style={{ marginBottom: '16px' }}
          >
            <Space direction="vertical" style={{ width: '100%' }}>
              <div>
                <Text type="secondary">Workflow ID</Text>
                <br />
                <Text strong>{analysis.workflowId || analysis.workflow_id || 'demo_workflow'}</Text>
              </div>
              
              <Divider />
              
              <div>
                <Text type="secondary">Analysis Time</Text>
                <br />
                <Text strong>{new Date(analysis.created_at || Date.now()).toLocaleString()}</Text>
              </div>
              
              <Divider />
              
              <Space>
                <Button 
                  icon={<FilePdfOutlined />} 
                  block 
                  disabled={analysis.upgradePrompt}
                  onClick={handleDownloadReport}
                >
                  Download Report {analysis.upgradePrompt && '(Pro)'}
                </Button>
              </Space>
            </Space>
          </Card>

          {/* Quick Stats */}
          <Card>
            <Title level={5}>Issue Breakdown</Title>
            <Space direction="vertical" style={{ width: '100%' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Space>
                  <Avatar style={{ backgroundColor: '#ff4d4f' }} size="small">C</Avatar>
                  <Text>Critical Issues</Text>
                </Space>
                <Text strong>
                  {analysis.issues?.filter((i: Issue) => i.type === 'critical').length || 0}
                </Text>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Space>
                  <Avatar style={{ backgroundColor: '#fa8c16' }} size="small">H</Avatar>
                  <Text>High Priority</Text>
                </Space>
                <Text strong>
                  {analysis.issues?.filter((i: Issue) => i.type === 'high').length || 0}
                </Text>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Space>
                  <Avatar style={{ backgroundColor: '#faad14' }} size="small">M</Avatar>
                  <Text>Medium Priority</Text>
                </Space>
                <Text strong>
                  {analysis.issues?.filter((i: Issue) => i.type === 'medium').length || 0}
                </Text>
              </div>
            </Space>
          </Card>
        </Col>
      </Row>

      <style>{`
        @keyframes fadeInUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
      `}</style>
    </div>
  );
};

// Helper function for Statistic component
interface StatisticProps {
  title: string;
  value: string | number;
  valueStyle?: React.CSSProperties;
  titleStyle?: React.CSSProperties;
}

const Statistic: React.FC<StatisticProps> = ({ title, value, valueStyle, titleStyle }) => (
  <div>
    <Text style={{ fontSize: '12px', color: '#8c8c8c', ...titleStyle }}>{title}</Text>
    <div style={{ fontSize: '24px', fontWeight: 'bold', ...valueStyle }}>{value}</div>
  </div>
);

export default Analysis;
